const movieDetailsTypes = {
  SET_MOVIE_DETAIL: "SET_MOVIE_DETAIL",
  LOADING_MOVIE_DETAIL: "LOADING_MOVIE_DETAIL",
  ERROR_LOADING_MOVIE_DETAIL: "ERROR_LOADING_MOVIE_DETAIL",
};

export default movieDetailsTypes;