const searchMoviesTypes = {
  SEARCHING_MOVIE: "SEARCHING_MOVIE",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
  ERROR_SEARCHING_MOVIES: "ERROR_SEARCHING_MOVIES",
  CLEAR_SEARCH_RESULTS: "CLEAR_SEARCH_RESULTS",
};

export default searchMoviesTypes;